CONFIG_GPIO=y
CONFIG_INPUT=y
CONFIG_INPUT_GPIO_QDEC=y
CONFIG_I2C=y
CONFIG_ADC=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_REBOOT=y
CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_APP_EVENT_MANAGER=y
CONFIG_CAF=y
CONFIG_CAF_BUTTONS=y
CONFIG_CAF_BUTTONS_DEF_PATH="src/buttons_def.h"
CONFIG_CAF_BUTTONS_PM_EVENTS=y
CONFIG_CAF_BUTTONS_PM_KEEP_ALIVE=y
CONFIG_CAF_POWER_MANAGER=y
CONFIG_CAF_POWER_MANAGER_TIMEOUT=60
CONFIG_CAF_POWER_MANAGER_STAY_ON=y
