CONFIG_GPIO=y
CONFIG_INPUT=y
CONFIG_INPUT_GPIO_QDEC=y
CONFIG_I2C=y
CONFIG_ADC=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_REBOOT=y
CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_APP_EVENT_MANAGER=y
CONFIG_APP_EVENT_MANAGER_SHOW_EVENTS=n
CONFIG_CAF=y
CONFIG_CAF_BUTTON_EVENTS=y
CONFIG_CAF_KEEP_ALIVE_EVENTS=y
CONFIG_CAF_MODULE_STATE_EVENTS=y
CONFIG_CAF_PM_EVENTS=y
CONFIG_CAF_POWER_MANAGER=y
CONFIG_CAF_POWER_MANAGER_TIMEOUT=60
CONFIG_CAF_POWER_MANAGER_STAY_ON=y
